/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.views;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author ITACHI
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null); 
        setTitle("Dashboard");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        add(new JLabel("Welcome to Hospital Management System!"));
        
    }
    private void closeAllInternalFrames() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
        frame.dispose(); // closes the frame
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPRegistration = new javax.swing.JMenuItem();
        menuPList = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDEntry = new javax.swing.JMenuItem();
        menuDList = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuAddRm = new javax.swing.JMenuItem();
        menuViewRm = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAddSvc = new javax.swing.JMenuItem();
        menuBilling = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPane)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktopPane)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Admin");

        menuNewUser.setText("New User");
        menuNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewUserActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Patients");

        menuPRegistration.setText("Registration");
        menuPRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPRegistrationActionPerformed(evt);
            }
        });
        jMenu2.add(menuPRegistration);

        menuPList.setText("Patient List");
        menuPList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPListActionPerformed(evt);
            }
        });
        jMenu2.add(menuPList);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Departments");

        jMenuItem1.setText("Department Creation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu3.setText("Doctors");

        menuDEntry.setText("Doctor Entry");
        menuDEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDEntryActionPerformed(evt);
            }
        });
        jMenu3.add(menuDEntry);

        menuDList.setText("Doctor List");
        menuDList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDListActionPerformed(evt);
            }
        });
        jMenu3.add(menuDList);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Rooms");

        menuAddRm.setText("Add Room");
        menuAddRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddRmActionPerformed(evt);
            }
        });
        jMenu4.add(menuAddRm);

        menuViewRm.setText("View Room");
        menuViewRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewRmActionPerformed(evt);
            }
        });
        jMenu4.add(menuViewRm);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Services");

        menuAddSvc.setText("Add Service");
        menuAddSvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddSvcActionPerformed(evt);
            }
        });
        jMenu5.add(menuAddSvc);

        menuBilling.setText("Billing");
        menuBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBillingActionPerformed(evt);
            }
        });
        jMenu5.add(menuBilling);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Logout");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu6.add(menuLogout);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu6.add(menuExit);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        this.dispose(); // Close dashboard
        new Login().setVisible(true); // Return to login screen
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBillingActionPerformed
        closeAllInternalFrames();
        Billing bill = new Billing();
        desktopPane.add(bill);
        bill.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBillingActionPerformed

    private void menuAddSvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddSvcActionPerformed
        closeAllInternalFrames();
        ServiceEntry svcentry = new ServiceEntry();
        desktopPane.add(svcentry);
        svcentry.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddSvcActionPerformed

    private void menuViewRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewRmActionPerformed
        closeAllInternalFrames();
        RoomList rmlist = new RoomList();
        desktopPane.add(rmlist);
        rmlist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuViewRmActionPerformed

    private void menuAddRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddRmActionPerformed
        closeAllInternalFrames();
        RoomManagement rmmgt = new RoomManagement(null);
        desktopPane.add(rmmgt);
        rmmgt.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddRmActionPerformed

    private void menuDListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDListActionPerformed
        closeAllInternalFrames();
        DoctorList drlist = new DoctorList();
        desktopPane.add(drlist);
        drlist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDListActionPerformed

    private void menuDEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDEntryActionPerformed
        closeAllInternalFrames();
        DoctorEntry drentry = new DoctorEntry();
        desktopPane.add(drentry);
        drentry.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDEntryActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        closeAllInternalFrames();
        DepartmentEntry dptentry = new DepartmentEntry();
        desktopPane.add(dptentry);
        dptentry.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuPListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPListActionPerformed
        closeAllInternalFrames();
        PatientList plist = new PatientList();
        desktopPane.add(plist);
        plist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPListActionPerformed

    private void menuPRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPRegistrationActionPerformed
        closeAllInternalFrames();
        PatientRegistration pr = new PatientRegistration();
        desktopPane.add(pr);
        pr.setSize(desktopPane.getWidth(), desktopPane.getHeight());
        pr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPRegistrationActionPerformed

    private void menuNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewUserActionPerformed
        closeAllInternalFrames();
        NewUser user = new NewUser();
        desktopPane.add(user);
        user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNewUserActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuAddRm;
    private javax.swing.JMenuItem menuAddSvc;
    private javax.swing.JMenuItem menuBilling;
    private javax.swing.JMenuItem menuDEntry;
    private javax.swing.JMenuItem menuDList;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuNewUser;
    private javax.swing.JMenuItem menuPList;
    private javax.swing.JMenuItem menuPRegistration;
    private javax.swing.JMenuItem menuViewRm;
    // End of variables declaration//GEN-END:variables
}
